type Group implements Node @resolver(isSelective: true, isBatching: true) {
  id: ID!
  name: String
  description: String
  parent: Group
  members: [Group!]!
}

type LookupOwner implements Node @resolver(isSelective: true) {
  id: ID!
  groups(first: Int, after: String, last: Int, before: String): GroupConnection! @resolver(isSelective: true)
}
type GroupEdge @edge { cursor: String!, node: Group! }
type GroupConnection @connection { edges: [GroupEdge!]!, pageInfo: PageInfo! }

input AddGroupInput {
  name: String!
}

type AddGroupPayload {
  group: Group
}

extend type Mutation {
  addGroup(input: AddGroupInput!): AddGroupPayload @resolver
  addGroupComposed(input: AddGroupInput!): AddGroupPayload @resolver
}

extend type Query {
  firstGroup: Group @resolver
  secondGroup: Group @resolver
  lookupGroups(name: String!, first: Int, after: String, last: Int, before: String): GroupConnection! @resolver(isSelective: true)
}
